# Generated by Django 2.2.4 on 2019-09-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_min',
            field=models.IntegerField(default=2),
        ),
    ]
